services:
  familychores-db:
    container_name: familychores-db
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - familychores-network
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U family_chores
      interval: 10s
      timeout: 5s
      retries: 5
  familychores-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - avatar_data:/data/avatars
      - backup_data:/data/backups
      - syslog_data:/data/syslogs
    networks:
      - familychores-network
    depends_on:
      familychores-db:
        condition: service_healthy
    restart: unless-stopped
networks:
  familychores-network:
    name: familychores-network
    driver: bridge
volumes:
  db_data:
  avatar_data:
  backup_data:
  syslog_data:
